/**
 * كتالوج فحوصات ابتدائي (٤٠ فحصًا شائعًا) يُحمَّل من صفحة الكتالوج.
 * المديات المرجعية تقريبية وللعرض التوضيحي — يجب أن يعتمدها مسؤول
 * الجودة وفق أجهزة المختبر والكواشف المستخدمة فعليًا قبل التشغيل.
 */

export type SeedRange = {
  sex?: "MALE" | "FEMALE";
  ageMinYears?: number;
  ageMaxYears?: number;
  low?: number;
  high?: number;
  text?: string;
};

export type SeedTest = {
  code: string;
  nameAr: string;
  nameEn: string;
  department:
    | "CHEMISTRY"
    | "HEMATOLOGY"
    | "IMMUNOLOGY"
    | "HORMONES"
    | "MICROBIOLOGY"
    | "URINALYSIS";
  resultType: "NUMERIC" | "TEXT" | "OPTION";
  unit?: string;
  sampleType?: string;
  tubeType?: string;
  price: number;
  options?: string[];
  ranges?: SeedRange[];
  criticalLow?: number;
  criticalHigh?: number;
  panelOf?: string[];
  sortOrder: number;
};

/* نوع العيّنة ونوع الأنبوب حقلان منفصلان: العيّنة تُقال للمريض («دم
   وريدي») والأنبوب تعليمة لفنّي السحب («بنفسجي EDTA»). دمجهما في نص
   واحد كان يمنع الفرز حسب الأنبوب وتحرير أحدهما دون الآخر.        */
const BLOOD = { sampleType: "دم وريدي", tubeType: "أنبوب أحمر (بلا مانع تخثر)" };
const EDTA = { sampleType: "دم وريدي", tubeType: "أنبوب بنفسجي (EDTA)" };
const CITRATE = { sampleType: "دم وريدي", tubeType: "أنبوب أزرق (سترات الصوديوم)" };
const URINE = { sampleType: "بول", tubeType: "حاوية بول معقّمة" };

export const SEED_TESTS: SeedTest[] = [
  /* ── الكيمياء الحيوية ─────────────────────────────────────── */
  {
    code: "GLU",
    nameAr: "سكر الدم صائم",
    nameEn: "Fasting Blood Glucose",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 15,
    ranges: [{ low: 70, high: 99 }],
    criticalLow: 45,
    criticalHigh: 450,
    sortOrder: 10,
  },
  {
    code: "HBA1C",
    nameAr: "السكر التراكمي",
    nameEn: "HbA1c",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "%",
    ...EDTA,
    price: 60,
    ranges: [{ low: 4, high: 5.6 }],
    sortOrder: 11,
  },
  {
    code: "UREA",
    nameAr: "اليوريا",
    nameEn: "Urea",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 15,
    ranges: [{ low: 15, high: 45 }],
    criticalHigh: 200,
    sortOrder: 12,
  },
  {
    code: "CREA",
    nameAr: "الكرياتينين",
    nameEn: "Creatinine",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 15,
    // `ageMinYears` على مديات البالغين مقصود: بدونه يطابق الطفلُ مدى
    // البالغين أيضًا، فيظهر كرياتينين ١.٠ عند طفل (مرتفع فعليًا) «طبيعيًا».
    ranges: [
      { sex: "MALE", ageMinYears: 15, low: 0.7, high: 1.3 },
      { sex: "FEMALE", ageMinYears: 15, low: 0.6, high: 1.1 },
      { ageMaxYears: 15, low: 0.3, high: 0.7 },
    ],
    criticalHigh: 7,
    sortOrder: 13,
  },
  {
    code: "URIC",
    nameAr: "حمض اليوريك",
    nameEn: "Uric Acid",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 18,
    ranges: [
      { sex: "MALE", low: 3.4, high: 7 },
      { sex: "FEMALE", low: 2.4, high: 6 },
    ],
    sortOrder: 14,
  },
  {
    code: "CHOL",
    nameAr: "الكوليسترول الكلي",
    nameEn: "Total Cholesterol",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 20,
    ranges: [{ high: 200 }],
    sortOrder: 20,
  },
  {
    code: "TG",
    nameAr: "الدهون الثلاثية",
    nameEn: "Triglycerides",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 20,
    ranges: [{ high: 150 }],
    criticalHigh: 1000,
    sortOrder: 21,
  },
  {
    code: "HDL",
    nameAr: "الكوليسترول النافع HDL",
    nameEn: "HDL Cholesterol",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 20,
    ranges: [
      { sex: "MALE", low: 40 },
      { sex: "FEMALE", low: 50 },
    ],
    sortOrder: 22,
  },
  {
    code: "LDL",
    nameAr: "الكوليسترول الضار LDL",
    nameEn: "LDL Cholesterol",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 20,
    ranges: [{ high: 130 }],
    sortOrder: 23,
  },
  {
    code: "AST",
    nameAr: "إنزيم الكبد AST",
    nameEn: "AST (SGOT)",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "U/L",
    ...BLOOD,
    price: 18,
    ranges: [
      { sex: "MALE", high: 40 },
      { sex: "FEMALE", high: 32 },
    ],
    sortOrder: 30,
  },
  {
    code: "ALT",
    nameAr: "إنزيم الكبد ALT",
    nameEn: "ALT (SGPT)",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "U/L",
    ...BLOOD,
    price: 18,
    ranges: [
      { sex: "MALE", high: 41 },
      { sex: "FEMALE", high: 33 },
    ],
    sortOrder: 31,
  },
  {
    code: "ALP",
    nameAr: "الفوسفاتيز القلوي",
    nameEn: "Alkaline Phosphatase",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "U/L",
    ...BLOOD,
    price: 18,
    ranges: [{ low: 40, high: 129 }],
    sortOrder: 32,
  },
  {
    code: "TBIL",
    nameAr: "البيليروبين الكلي",
    nameEn: "Total Bilirubin",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 15,
    ranges: [{ low: 0.2, high: 1.2 }],
    criticalHigh: 15,
    sortOrder: 33,
  },
  {
    code: "DBIL",
    nameAr: "البيليروبين المباشر",
    nameEn: "Direct Bilirubin",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 15,
    ranges: [{ high: 0.3 }],
    sortOrder: 34,
  },
  {
    code: "ALB",
    nameAr: "الألبومين",
    nameEn: "Albumin",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "g/dL",
    ...BLOOD,
    price: 15,
    ranges: [{ low: 3.5, high: 5.2 }],
    sortOrder: 35,
  },
  {
    code: "TP",
    nameAr: "البروتين الكلي",
    nameEn: "Total Protein",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "g/dL",
    ...BLOOD,
    price: 15,
    ranges: [{ low: 6.4, high: 8.3 }],
    sortOrder: 36,
  },
  {
    code: "NA",
    nameAr: "الصوديوم",
    nameEn: "Sodium",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mmol/L",
    ...BLOOD,
    price: 20,
    ranges: [{ low: 136, high: 145 }],
    criticalLow: 120,
    criticalHigh: 160,
    sortOrder: 40,
  },
  {
    code: "K",
    nameAr: "البوتاسيوم",
    nameEn: "Potassium",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mmol/L",
    ...BLOOD,
    price: 20,
    ranges: [{ low: 3.5, high: 5.1 }],
    criticalLow: 2.5,
    criticalHigh: 6.5,
    sortOrder: 41,
  },
  {
    code: "CL",
    nameAr: "الكلورايد",
    nameEn: "Chloride",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mmol/L",
    ...BLOOD,
    price: 20,
    ranges: [{ low: 98, high: 107 }],
    sortOrder: 42,
  },
  {
    code: "CA",
    nameAr: "الكالسيوم",
    nameEn: "Calcium",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "mg/dL",
    ...BLOOD,
    price: 20,
    ranges: [{ low: 8.6, high: 10.2 }],
    criticalLow: 6.5,
    criticalHigh: 13,
    sortOrder: 43,
  },
  {
    code: "AMY",
    nameAr: "الأميليز",
    nameEn: "Amylase",
    department: "CHEMISTRY",
    resultType: "NUMERIC",
    unit: "U/L",
    ...BLOOD,
    price: 30,
    ranges: [{ low: 28, high: 100 }],
    sortOrder: 44,
  },

  /* ── أمراض الدم ───────────────────────────────────────────── */
  {
    code: "CBC",
    nameAr: "صورة الدم الكاملة",
    nameEn: "Complete Blood Count",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    ...EDTA,
    price: 45,
    panelOf: ["WBC", "RBC", "HGB", "HCT", "MCV", "MCH", "PLT"],
    sortOrder: 50,
  },
  {
    code: "WBC",
    nameAr: "كريات الدم البيضاء",
    nameEn: "WBC",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "10³/µL",
    ...EDTA,
    price: 0,
    ranges: [{ low: 4, high: 11 }],
    criticalLow: 1.5,
    criticalHigh: 30,
    sortOrder: 51,
  },
  {
    code: "RBC",
    nameAr: "كريات الدم الحمراء",
    nameEn: "RBC",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "10⁶/µL",
    ...EDTA,
    price: 0,
    ranges: [
      { sex: "MALE", low: 4.5, high: 5.9 },
      { sex: "FEMALE", low: 4.1, high: 5.1 },
    ],
    sortOrder: 52,
  },
  {
    code: "HGB",
    nameAr: "الهيموغلوبين",
    nameEn: "Hemoglobin",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "g/dL",
    ...EDTA,
    price: 0,
    ranges: [
      { sex: "MALE", ageMinYears: 12, low: 13.5, high: 17.5 },
      { sex: "FEMALE", ageMinYears: 12, low: 12, high: 15.5 },
      { ageMaxYears: 12, low: 11.5, high: 15.5 },
    ],
    criticalLow: 7,
    criticalHigh: 20,
    sortOrder: 53,
  },
  {
    code: "HCT",
    nameAr: "الهيماتوكريت",
    nameEn: "Hematocrit",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "%",
    ...EDTA,
    price: 0,
    ranges: [
      { sex: "MALE", low: 41, high: 53 },
      { sex: "FEMALE", low: 36, high: 46 },
    ],
    criticalLow: 21,
    sortOrder: 54,
  },
  {
    code: "MCV",
    nameAr: "متوسط حجم الكرية",
    nameEn: "MCV",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "fL",
    ...EDTA,
    price: 0,
    ranges: [{ low: 80, high: 100 }],
    sortOrder: 55,
  },
  {
    code: "MCH",
    nameAr: "متوسط هيموغلوبين الكرية",
    nameEn: "MCH",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "pg",
    ...EDTA,
    price: 0,
    ranges: [{ low: 27, high: 33 }],
    sortOrder: 56,
  },
  {
    code: "PLT",
    nameAr: "الصفائح الدموية",
    nameEn: "Platelets",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "10³/µL",
    ...EDTA,
    price: 0,
    ranges: [{ low: 150, high: 450 }],
    criticalLow: 50,
    criticalHigh: 1000,
    sortOrder: 57,
  },
  {
    code: "ESR",
    nameAr: "سرعة ترسيب الدم",
    nameEn: "ESR",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "mm/hr",
    ...EDTA,
    price: 20,
    ranges: [
      { sex: "MALE", high: 15 },
      { sex: "FEMALE", high: 20 },
    ],
    sortOrder: 58,
  },
  {
    code: "PT",
    nameAr: "زمن البروثرومبين",
    nameEn: "Prothrombin Time",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    unit: "sec",
    ...CITRATE,
    price: 35,
    ranges: [{ low: 11, high: 13.5 }],
    sortOrder: 59,
  },
  {
    code: "INR",
    nameAr: "النسبة المعيارية INR",
    nameEn: "INR",
    department: "HEMATOLOGY",
    resultType: "NUMERIC",
    ...CITRATE,
    price: 25,
    ranges: [{ low: 0.8, high: 1.2 }],
    criticalHigh: 5,
    sortOrder: 60,
  },

  /* ── الهرمونات ────────────────────────────────────────────── */
  {
    code: "TSH",
    nameAr: "هرمون الغدة الدرقية TSH",
    nameEn: "TSH",
    department: "HORMONES",
    resultType: "NUMERIC",
    unit: "µIU/mL",
    ...BLOOD,
    price: 55,
    ranges: [{ low: 0.4, high: 4.2 }],
    sortOrder: 70,
  },
  {
    code: "FT4",
    nameAr: "الثيروكسين الحر FT4",
    nameEn: "Free T4",
    department: "HORMONES",
    resultType: "NUMERIC",
    unit: "ng/dL",
    ...BLOOD,
    price: 55,
    ranges: [{ low: 0.8, high: 1.8 }],
    sortOrder: 71,
  },
  {
    code: "BHCG",
    nameAr: "هرمون الحمل الكمّي",
    nameEn: "Beta-hCG",
    department: "HORMONES",
    resultType: "NUMERIC",
    unit: "mIU/mL",
    ...BLOOD,
    price: 70,
    ranges: [{ high: 5, text: "< 5 (غير حامل)" }],
    sortOrder: 72,
  },
  {
    code: "VITD",
    nameAr: "فيتامين د",
    nameEn: "Vitamin D (25-OH)",
    department: "HORMONES",
    resultType: "NUMERIC",
    unit: "ng/mL",
    ...BLOOD,
    price: 90,
    ranges: [{ low: 30, high: 100 }],
    sortOrder: 73,
  },
  {
    code: "FERR",
    nameAr: "الفيريتين",
    nameEn: "Ferritin",
    department: "HORMONES",
    resultType: "NUMERIC",
    unit: "ng/mL",
    ...BLOOD,
    price: 65,
    ranges: [
      { sex: "MALE", low: 30, high: 400 },
      { sex: "FEMALE", low: 13, high: 150 },
    ],
    sortOrder: 74,
  },

  /* ── المناعة والمصليات ────────────────────────────────────── */
  {
    code: "CRP",
    nameAr: "البروتين التفاعلي CRP",
    nameEn: "C-Reactive Protein",
    department: "IMMUNOLOGY",
    resultType: "NUMERIC",
    unit: "mg/L",
    ...BLOOD,
    price: 35,
    ranges: [{ high: 6 }],
    sortOrder: 80,
  },
  {
    code: "HBSAG",
    nameAr: "الالتهاب الكبدي B",
    nameEn: "HBsAg",
    department: "IMMUNOLOGY",
    resultType: "OPTION",
    ...BLOOD,
    price: 40,
    options: ["سلبي", "إيجابي"],
    ranges: [{ text: "سلبي" }],
    sortOrder: 81,
  },
  {
    code: "HCVAB",
    nameAr: "الالتهاب الكبدي C",
    nameEn: "HCV Ab",
    department: "IMMUNOLOGY",
    resultType: "OPTION",
    ...BLOOD,
    price: 45,
    options: ["سلبي", "إيجابي"],
    ranges: [{ text: "سلبي" }],
    sortOrder: 82,
  },
  {
    code: "RF",
    nameAr: "العامل الروماتويدي",
    nameEn: "Rheumatoid Factor",
    department: "IMMUNOLOGY",
    resultType: "OPTION",
    ...BLOOD,
    price: 35,
    options: ["سلبي", "إيجابي"],
    ranges: [{ text: "سلبي" }],
    sortOrder: 83,
  },

  /* ── البول والأحياء الدقيقة ───────────────────────────────── */
  {
    code: "URINE",
    nameAr: "تحليل بول عام",
    nameEn: "Urine Analysis",
    department: "URINALYSIS",
    resultType: "TEXT",
    ...URINE,
    price: 25,
    ranges: [{ text: "طبيعي" }],
    sortOrder: 90,
  },
  {
    code: "PREG",
    nameAr: "اختبار الحمل (بول)",
    nameEn: "Urine Pregnancy Test",
    department: "URINALYSIS",
    resultType: "OPTION",
    ...URINE,
    price: 20,
    options: ["سلبي", "إيجابي"],
    ranges: [{ text: "سلبي" }],
    sortOrder: 91,
  },
  {
    code: "UCULT",
    nameAr: "مزرعة بول وحساسية",
    nameEn: "Urine Culture & Sensitivity",
    department: "MICROBIOLOGY",
    resultType: "TEXT",
    ...URINE,
    price: 80,
    ranges: [{ text: "لا يوجد نمو بكتيري" }],
    sortOrder: 92,
  },
];
